/**
 * Demo seed data — realistic credit union breach examples based on
 * publicly reported incidents (names and details are illustrative).
 */

const { upsertBreach } = require('../db');

const DEMO_BREACHES = [
  {
    external_id: 'demo-001',
    organization: 'Patelco Credit Union',
    state: 'CA',
    breach_date: '2024-06-29',
    notification_date: '2024-07-26',
    breach_type: 'Ransomware',
    attack_vector: 'Third-Party',
    records_affected: 726000,
    data_types: 'SSN, Date of Birth, Driver\'s License, Account Number, Financial Information',
    source: 'DataBreaches.net',
    source_url: 'https://www.databreaches.net',
    description: 'RansomHub ransomware attack disrupted online banking services for 2 weeks. Member data compromised including SSNs and financial information.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-002',
    organization: 'Truliant Federal Credit Union',
    state: 'NC',
    breach_date: '2023-11-15',
    notification_date: '2024-01-10',
    breach_type: 'Unauthorized Access/Hacking',
    attack_vector: 'Web Application',
    records_affected: 189000,
    data_types: 'SSN, Account Number, Financial Information, Address',
    source: 'Maine AG',
    source_url: 'https://www.maine.gov/agviewer',
    description: 'Unauthorized access to member data through compromised vendor portal. Attackers accessed loan application data.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-003',
    organization: 'Consumers Credit Union',
    state: 'IL',
    breach_date: '2023-08-01',
    notification_date: '2023-09-22',
    breach_type: 'Third-Party/Vendor',
    attack_vector: 'Third-Party',
    records_affected: 53000,
    data_types: 'Name, Address, SSN, Account Number',
    source: 'California AG',
    source_url: 'https://oag.ca.gov/privacy/databreach/list',
    description: 'MOVEit Transfer vulnerability exploited by Cl0p ransomware group via third-party service provider affecting member records.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-004',
    organization: 'Northwest Federal Credit Union',
    state: 'VA',
    breach_date: '2023-06-15',
    notification_date: '2023-08-02',
    breach_type: 'Phishing',
    attack_vector: 'Email/Phishing',
    records_affected: 12400,
    data_types: 'Email, Credentials, Account Information',
    source: 'KrebsOnSecurity',
    source_url: 'https://krebsonsecurity.com',
    description: 'Business email compromise campaign targeted employees. Attackers used compromised credentials to access member account data.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-005',
    organization: 'Lake Shore Savings Federal Credit Union',
    state: 'NY',
    breach_date: '2023-04-03',
    notification_date: '2023-05-18',
    breach_type: 'Ransomware',
    attack_vector: 'Remote Access',
    records_affected: 8900,
    data_types: 'SSN, Financial Account, Address, Date of Birth',
    source: 'Maine AG',
    source_url: 'https://www.maine.gov/agviewer',
    description: 'LockBit ransomware attack encrypted core banking systems. Member data exfiltrated prior to encryption.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-006',
    organization: 'Los Angeles Federal Credit Union',
    state: 'CA',
    breach_date: '2022-12-01',
    notification_date: '2023-01-15',
    breach_type: 'Unauthorized Access/Hacking',
    attack_vector: 'Web Application',
    records_affected: 31500,
    data_types: 'Online Banking Credentials, Account Numbers, Email',
    source: 'California AG',
    source_url: 'https://oag.ca.gov/privacy/databreach/list',
    description: 'Credential stuffing attack against online banking portal resulted in unauthorized account access.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-007',
    organization: 'Teachers Federal Credit Union',
    state: 'NY',
    breach_date: '2022-09-14',
    notification_date: '2022-10-28',
    breach_type: 'Third-Party/Vendor',
    attack_vector: 'Third-Party',
    records_affected: 95000,
    data_types: 'SSN, Account Number, Loan Information, Address',
    source: 'ITRC',
    source_url: 'https://www.idtheftcenter.org',
    description: 'Breach at mortgage service vendor exposed member loan application data. Third-party provider failed to implement adequate access controls.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-008',
    organization: 'Ent Credit Union',
    state: 'CO',
    breach_date: '2022-07-01',
    notification_date: '2022-08-10',
    breach_type: 'Insider Threat',
    attack_vector: 'Insider',
    records_affected: 4200,
    data_types: 'SSN, Account Number, Financial Information',
    source: 'NCUA',
    source_url: 'https://www.ncua.gov',
    description: 'Former employee accessed and exfiltrated member data after termination using retained credentials.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-009',
    organization: 'Travis Credit Union',
    state: 'CA',
    breach_date: '2022-03-22',
    notification_date: '2022-05-09',
    breach_type: 'Malware',
    attack_vector: 'Email/Phishing',
    records_affected: 27800,
    data_types: 'Name, Address, SSN, Account Number, Date of Birth',
    source: 'California AG',
    source_url: 'https://oag.ca.gov/privacy/databreach/list',
    description: 'Information-stealing malware deployed via spear phishing email targeting finance department.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-010',
    organization: 'Mountain America Federal Credit Union',
    state: 'UT',
    breach_date: '2021-11-01',
    notification_date: '2021-12-17',
    breach_type: 'Accidental Exposure',
    attack_vector: null,
    records_affected: 15600,
    data_types: 'Account Number, Transaction History, Email',
    source: 'DataBreaches.net',
    source_url: 'https://www.databreaches.net',
    description: 'Misconfigured cloud storage bucket exposed member transaction records. No evidence of unauthorized access.',
    status: 'resolved',
    is_manual: 0,
  },
  {
    external_id: 'demo-011',
    organization: 'Suncoast Credit Union',
    state: 'FL',
    breach_date: '2021-08-15',
    notification_date: '2021-09-30',
    breach_type: 'Ransomware',
    attack_vector: 'Remote Access',
    records_affected: 142000,
    data_types: 'SSN, Account Number, Loan Information, Health Information',
    source: 'BankInfoSecurity',
    source_url: 'https://www.bankinfosecurity.com',
    description: 'Hive ransomware attack via compromised VPN credentials. Extended system outage affected member services for 5 days.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-012',
    organization: 'Affinity Plus Federal Credit Union',
    state: 'MN',
    breach_date: '2021-05-03',
    notification_date: '2021-06-22',
    breach_type: 'Third-Party/Vendor',
    attack_vector: 'Third-Party',
    records_affected: 38900,
    data_types: 'SSN, Financial Account, Driver\'s License',
    source: 'Maine AG',
    source_url: 'https://www.maine.gov/agviewer',
    description: 'Print/mail vendor breach exposed member statement data during a supply chain attack.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-013',
    organization: 'BECU (Boeing Employees Credit Union)',
    state: 'WA',
    breach_date: '2023-05-31',
    notification_date: '2023-07-14',
    breach_type: 'Third-Party/Vendor',
    attack_vector: 'Third-Party',
    records_affected: 58000,
    data_types: 'SSN, Account Number, Address, Date of Birth',
    source: 'ITRC',
    source_url: 'https://www.idtheftcenter.org',
    description: 'MOVEit file transfer software exploit (CVE-2023-34362) impacted third-party vendor handling member data.',
    status: 'active',
    is_manual: 0,
  },
  {
    external_id: 'demo-014',
    organization: 'Golden 1 Credit Union',
    state: 'CA',
    breach_date: '2020-09-01',
    notification_date: '2020-10-27',
    breach_type: 'Phishing',
    attack_vector: 'Email/Phishing',
    records_affected: 23400,
    data_types: 'Credentials, Account Information, Email',
    source: 'California AG',
    source_url: 'https://oag.ca.gov/privacy/databreach/list',
    description: 'Targeted phishing campaign compromised employee credentials enabling access to member account data.',
    status: 'resolved',
    is_manual: 0,
  },
  {
    external_id: 'demo-015',
    organization: 'First Tech Federal Credit Union',
    state: 'OR',
    breach_date: '2024-02-08',
    notification_date: '2024-03-22',
    breach_type: 'Unauthorized Access/Hacking',
    attack_vector: 'Web Application',
    records_affected: 78500,
    data_types: 'SSN, Account Number, Financial Information, Address',
    source: 'DataBreaches.net',
    source_url: 'https://www.databreaches.net',
    description: 'Attackers exploited API vulnerability in mobile banking application to access member accounts.',
    status: 'active',
    is_manual: 0,
  },
];

async function seedDemoData() {
  let seeded = 0;
  for (const breach of DEMO_BREACHES) {
    const { isNew } = upsertBreach(breach);
    if (isNew) seeded++;
  }
  console.log(`[Seed] ${seeded} demo breaches seeded (${DEMO_BREACHES.length - seeded} already existed)`);
  return seeded;
}

module.exports = { seedDemoData, DEMO_BREACHES };
